name = "hdjrz-license"
main = "backend/worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "LICENSES", id = "LICENSES_ID_PLACEHOLDER" }
]

[[d1_databases]]
binding = "DB"
database_name = "hdjrz-support"
database_id = "2694104f-b9f7-4b99-81db-b5c27a5a2040"
